@startuml
hide empty members
entity "Discounts" as Discounts{
    <<PK>> ID: int
    ---
    NumberOfCatsEnabledFrom: int
    DiscountCZK: int
    DiscountEUR: int
}

"Exhibitions" ||--o{ "Discounts"
"Discounts" }o--o{ "CatRegistrations"
@enduml