name: Sync Repos

on:
  push:
    branches:
      - sync

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2

      - name: Push to destination repository
        run: |
          git config --global user.email "ondrejman1@gmail.com"
          git config --global user.name "ondrejman1@gmail.com"
          git clone https://${{ env.ORG_NAME }}:${{ secrets.OMAN }}@github.com/${{ env.ORG_NAME }}/RegisterMePublic.git
          cd RegisterMePublic
          git remote add ${{ env.ORIGINAL_REPO_NAME }} https://${{ env.ORG_NAME }}:${{ secrets.OMAN }}@github.com/${{ env.ORG_NAME }}/${{ env.ORIGINAL_REPO_NAME }}.git
          git remote update
          git reset --hard ${{ env.ORIGINAL_REPO_NAME }}/sync
          cd RegisterMe
          rm .env.docker
          rm .env.production
          rm .env.development
          git add .
          git commit -m "Delete envs"
          git reset $(git commit-tree HEAD^{tree} -m "Initial")
          git push -f origin main
        env:
          GITHUB_TOKEN: ${{ secrets.OMAN }}
          ORIGINAL_REPO_NAME: ${{ github.event.repository.name }}
          ORG_NAME: ManasComp
          